### ISSUE TITLE
[request] update text when VimResized

### ISSUE THREAD

**Issue by sunn4room** [cameron-wags/splash.nvim#3]
My wm is i3, and window size is unfixed. So, I think a "VimResized" autocmd should be added.

In addition, it is just personal preference:

https://github.com/cameron-wags/splash.nvim/blob/69947f826b326e8466293d2512682282e4293509/lua/splash/init.lua#L10
should use vim.api.nvim_win_get_width

https://github.com/cameron-wags/splash.nvim/blob/69947f826b326e8466293d2512682282e4293509/lua/splash/init.lua#L23
should use vim.api.nvim_win_get_height

**Comment by cameron-wags** [comment]
Resizing is a good idea, thanks for the suggestion.
I had no clue those functions existed! Definitely a nicer way to do it.
ce124437d4ff3fdf55fa4d3e9bf890fca7d79761 Hopefully takes care of both.
